### ISSUE TITLE
Print correct time step

### ISSUE THREAD

**Issue by usshmah** [modern-fortran/tsunami#18]
On line https://github.com/modern-fortran/tsunami/blob/d325ec5779461b56ae0714c4e068e056fa3fda16/src/ch02/tsunami.f90#L55 you print zero for each time step. It should be `print fmt, n, h` instead.

**Comment by milancurcic** [comment]
Indeed, thanks for reporting it! This was introduced in https://github.com/modern-fortran/tsunami/commit/2440f85332f0e03390fe1fc152c0e7765082a919 in a bad case of copy paste.
